Paywalls: Small optimization purchase button
RevenueCat/purchases-android pull request #1375
Opened 2023-10-19 20:30 UTC by tonidero

### Description
This changes the animations for the purchase button to use `AnimatedVisibility` which actually removes the composable when the animation ends, making sure the progress indicator is not rendered without need, causing CPU usage

2023-10-19 20:34 UTC, NachoSoto approved these changes

2023-10-19 20:34 UTC, NachoSoto commented on ui/revenuecatui/src/main/kotlin/com/revenuecat/purchases/ui/revenuecatui/composables/PurchaseButton.kt
> +    AnimatedVisibility(
<3 this is so much better

2023-10-19 20:35 UTC, NachoSoto commented
This is a huge find, thank you @tonidero! 🙏🏻

2023-10-19 20:44 UTC, NachoSoto requested changes
Actually I think we need to use the existing implementation

I was in the process of changing `ConsistentPackageContentView` to use `AnimatedVisibility` as well, but I realized that it removes elements from the layout. It's important that we don't do that because we need them to be hidden and contribute to the overall layout so that package transitions are consistent and don't move content around.

2023-10-19 20:54 UTC, tonidero commented
Oh hmm then maybe we can use it only for the progress indicator, which was causing the issue? Will confirm tomorrow, thanks for catching that?

2023-10-19 20:57 UTC, NachoSoto commented
I noticed that the purchase button was changing height now because of that as well.
I'm trying to find another solution for this 🙏🏻  no worries though, we'll figure this out! Thanks for finding the source of the performance issue.

2023-10-19 21:39 UTC, NachoSoto commented
@tonidero new approach: https://github.com/RevenueCat/purchases-android/pull/1376

2023-10-20 07:13 UTC, tonidero commented
Closing in favor of #1376

2023-10-20 07:13 UTC, closed without merging