Redo rename PurchaseOption -> SubscriptionOption
RevenueCat/purchases-android pull request #749
Opened 2023-01-20 21:10 UTC by beylmk

https://github.com/RevenueCat/purchases-android/pull/735 was reverted for ease of merging https://github.com/RevenueCat/purchases-android/pull/739

This just reapplies the rename

2023-01-23 10:42 UTC, joshdholtz requested changes
Yesssss... thank you for doing this! I think the only thing that is needed here is updating the `v6-MIGRATION.md` with the rename

Other than that this is 💯

2023-01-23 14:20 UTC, beylmk commented
>I think the only thing that is needed here is updating the `v6-MIGRATION.md` with the rename

@joshdholtz i _think_ i got all references in `v6-migration`... do you see one i didn't get? could be my monday brain missing something..

2023-01-24 12:58 UTC, joshdholtz commented
@beylmk Oh, it did but I thought it got reverted! I swear I looked and saw that it did get reverted back but maybe that was my Monday brain 😅 This looks all good!

2023-01-24 12:58 UTC, joshdholtz approved these changes

2023-01-24 15:19 UTC, merged